const N = [
  ['af','Afeganistão','Afghanistan'],
  ['za','África do Sul','South Africa'],
  ['al','Albânia','Albania'],
  ['de','Alemanha','Germany'],
  ['ad','Andorra','Andorra'],
  ['ao','Angola','Angola'],
  ['ag','Antígua e Barbuda','Antigua and Barbuda'],
  ['sa','Arábia Saudita','Saudi Arabia'],
  ['dz','Argélia','Algeria'],
  ['ar','Argentina','Argentina'],
  ['am','Armênia','Armenia'],
  ['au','Austrália','Australia'],
  ['at','Áustria','Austria'],
  ['az','Azerbaijão','Azerbaijan'],
  ['bs','Bahamas','Bahamas'],
  ['bh','Bahrein','Bahrain'],
  ['bd','Bangladesh','Bangladesh'],
  ['bb','Barbados','Barbados'],
  ['by','Belarus','Belarus'],
  ['be','Bélgica','Belgium'],
  ['bz','Belize','Belize'],
  ['bj','Benim','Benin'],
  ['bt','Butão','Bhutan'],
  ['bo','Bolívia','Bolivia'],
  ['ba','Bósnia e Herzegovina','Bosnia and Herzegovina'],
  ['bw','Botsuana','Botswana'],
  ['br','Brasil','Brazil'],
  ['bn','Brunei','Brunei'],
  ['bg','Bulgária','Bulgaria'],
  ['bf','Burkina Faso','Burkina Faso'],
  ['bi','Burundi','Burundi'],
  ['cv','Cabo Verde','Cabo Verde'],
  ['kh','Camboja','Cambodia'],
  ['cm','Camarões','Cameroon'],
  ['ca','Canadá','Canada'],
  ['qa','Catar','Qatar'],
  ['kz','Cazaquistão','Kazakhstan'],
  ['td','Chade','Chad'],
  ['cl','Chile','Chile'],
  ['cn','China','China'],
  ['cy','Chipre','Cyprus'],
  ['co','Colômbia','Colombia'],
  ['km','Comores','Comoros'],
  ['cg','Congo','Congo'],
  ['cd','República Democrática do Congo','Democratic Republic of the Congo'],
  ['kp','Coreia do Norte','North Korea'],
  ['kr','Coreia do Sul','South Korea'],
  ['ci','Costa do Marfim','Ivory Coast'],
  ['cr','Costa Rica','Costa Rica'],
  ['hr','Croácia','Croatia'],
  ['cu','Cuba','Cuba'],
  ['dk','Dinamarca','Denmark'],
  ['dj','Djibuti','Djibouti'],
  ['dm','Dominica','Dominica'],
  ['do','República Dominicana','Dominican Republic'],
  ['eg','Egito','Egypt'],
  ['sv','El Salvador','El Salvador'],
  ['ae','Emirados Árabes Unidos','United Arab Emirates'],
  ['ec','Equador','Ecuador'],
  ['er','Eritreia','Eritrea'],
  ['sk','Eslováquia','Slovakia'],
  ['si','Eslovênia','Slovenia'],
  ['es','Espanha','Spain'],
  ['us','Estados Unidos','United States','USA','US'],
  ['ee','Estônia','Estonia'],
  ['sz','Essuatíni','Eswatini'],
  ['et','Etiópia','Ethiopia'],
  ['fj','Fiji','Fiji'],
  ['ph','Filipinas','Philippines'],
  ['fi','Finlândia','Finland'],
  ['fr','França','France'],
  ['ga','Gabão','Gabon'],
  ['gm','Gâmbia','Gambia'],
  ['gh','Gana','Ghana'],
  ['ge','Geórgia','Georgia'],
  ['gd','Granada','Grenada'],
  ['gr','Grécia','Greece'],
  ['gt','Guatemala','Guatemala'],
  ['gn','Guiné','Guinea'],
  ['gw','Guiné-Bissau','Guinea-Bissau'],
  ['gq','Guiné Equatorial','Equatorial Guinea'],
  ['gy','Guiana','Guyana'],
  ['ht','Haiti','Haiti'],
  ['hn','Honduras','Honduras'],
  ['hu','Hungria','Hungary'],
  ['ye','Iêmen','Yemen'],
  ['mh','Ilhas Marshall','Marshall Islands'],
  ['sb','Ilhas Salomão','Solomon Islands'],
  ['in','Índia','India'],
  ['id','Indonésia','Indonesia'],
  ['ir','Irã','Iran'],
  ['iq','Iraque','Iraq'],
  ['ie','Irlanda','Ireland'],
  ['is','Islândia','Iceland'],
  ['il','Israel','Israel'],
  ['it','Itália','Italy'],
  ['jm','Jamaica','Jamaica'],
  ['jp','Japão','Japan'],
  ['jo','Jordânia','Jordan'],
  ['ke','Quênia','Kenya'],
  ['ki','Kiribati','Kiribati'],
  ['kw','Kuwait','Kuwait'],
  ['kg','Quirguistão','Kyrgyzstan'],
  ['la','Laos','Laos'],
  ['lv','Letônia','Latvia'],
  ['lb','Líbano','Lebanon'],
  ['ls','Lesoto','Lesotho'],
  ['lr','Libéria','Liberia'],
  ['ly','Líbia','Libya'],
  ['li','Liechtenstein','Liechtenstein'],
  ['lt','Lituânia','Lithuania'],
  ['lu','Luxemburgo','Luxembourg'],
  ['mk','Macedônia do Norte','North Macedonia'],
  ['mg','Madagascar','Madagascar'],
  ['mw','Malawi','Malawi'],
  ['my','Malásia','Malaysia'],
  ['mv','Maldivas','Maldives'],
  ['ml','Mali','Mali'],
  ['mt','Malta','Malta'],
  ['ma','Marrocos','Morocco'],
  ['mu','Maurício','Mauritius'],
  ['mr','Mauritânia','Mauritania'],
  ['mx','México','Mexico'],
  ['fm','Micronésia','Micronesia'],
  ['md','Moldávia','Moldova'],
  ['mc','Mônaco','Monaco'],
  ['mn','Mongólia','Mongolia'],
  ['me','Montenegro','Montenegro'],
  ['mz','Moçambique','Mozambique'],
  ['mm','Mianmar','Myanmar'],
  ['na','Namíbia','Namibia'],
  ['nr','Nauru','Nauru'],
  ['np','Nepal','Nepal'],
  ['nl','Países Baixos','Netherlands','Holland'],
  ['nz','Nova Zelândia','New Zealand'],
  ['ni','Nicarágua','Nicaragua'],
  ['ne','Níger','Niger'],
  ['ng','Nigéria','Nigeria'],
  ['no','Noruega','Norway'],
  ['om','Omã','Oman'],
  ['pk','Paquistão','Pakistan'],
  ['pw','Palau','Palau'],
  ['ps','Palestina','Palestine'],
  ['pa','Panamá','Panama'],
  ['pg','Papua-Nova Guiné','Papua New Guinea'],
  ['py','Paraguai','Paraguay'],
  ['pe','Peru','Peru'],
  ['pl','Polônia','Poland'],
  ['pt','Portugal','Portugal'],
  ['cf','República Centro-Africana','Central African Republic'],
  ['cz','República Tcheca','Czech Republic','Czechia'],
  ['ro','Romênia','Romania'],
  ['ru','Rússia','Russia'],
  ['rw','Ruanda','Rwanda'],
  ['kn','São Cristóvão e Névis','Saint Kitts and Nevis'],
  ['lc','Santa Lúcia','Saint Lucia'],
  ['vc','São Vicente e Granadinas','Saint Vincent and the Grenadines'],
  ['ws','Samoa','Samoa'],
  ['sm','San Marino','San Marino'],
  ['st','São Tomé e Príncipe','Sao Tome and Principe'],
  ['sc','Seicheles','Seychelles'],
  ['sn','Senegal','Senegal'],
  ['rs','Sérvia','Serbia'],
  ['sl','Serra Leoa','Sierra Leone'],
  ['sg','Singapura','Singapore'],
  ['sy','Síria','Syria'],
  ['so','Somália','Somalia'],
  ['lk','Sri Lanka','Sri Lanka'],
  ['sd','Sudão','Sudan'],
  ['ss','Sudão do Sul','South Sudan'],
  ['se','Suécia','Sweden'],
  ['ch','Suíça','Switzerland'],
  ['sr','Suriname','Suriname'],
  ['tj','Tajiquistão','Tajikistan'],
  ['tz','Tanzânia','Tanzania'],
  ['th','Tailândia','Thailand'],
  ['tl','Timor-Leste','Timor-Leste'],
  ['tg','Togo','Togo'],
  ['to','Tonga','Tonga'],
  ['tt','Trinidad e Tobago','Trinidad and Tobago'],
  ['tn','Tunísia','Tunisia'],
  ['tm','Turcomenistão','Turkmenistan'],
  ['tr','Turquia','Turkey'],
  ['tv','Tuvalu','Tuvalu'],
  ['ug','Uganda','Uganda'],
  ['ua','Ucrânia','Ukraine'],
  ['gb','Reino Unido','United Kingdom','UK'],
  ['uy','Uruguai','Uruguay'],
  ['uz','Uzbequistão','Uzbekistan'],
  ['vu','Vanuatu','Vanuatu'],
  ['va','Vaticano','Vatican City'],
  ['ve','Venezuela','Venezuela'],
  ['vn','Vietnã','Vietnam'],
  ['zm','Zâmbia','Zambia'],
  ['zw','Zimbábue','Zimbabwe']
];

const flag = id => [...id.toUpperCase()].map(c => String.fromCodePoint(127397 + c.charCodeAt(0))).join('');

const countries = N.map(([id, name, ...englishNames]) => ({
  id,
  name,
  flag: flag(id),
  aliases: [
    name.toLowerCase(),
    ...englishNames.map(n => n.toLowerCase())
  ]
}));

countries.push(
  {id: 'jp-imperial', name: 'Japão Imperial', flagAsset: 'assets/flags/japan-imperial.svg', aliases: ['japao imperial','japão imperial','imperial japan']},
  {id: 'ussr', name: 'União Soviética', flagAsset: 'assets/flags/ussr.svg', aliases: ['uniao sovietica','união soviética','urss','ussr','soviet union','ussr']}
);

window.COUNTRIES = countries;